
CREATE TABLE IF NOT EXISTS Room (id INT NOT NULL, coverImageSrc VARCHAR(45) NULL, PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS Language (id INT NOT NULL, language VARCHAR(2) NOT NULL, countryCode VARCHAR(2) NOT NULL, PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS RoomLanguage (id INT NOT NULL, idRoom INT NOT NULL, idLanguage INT NOT NULL, name VARCHAR(100) NOT NULL, description VARCHAR(500) NULL, PRIMARY KEY (id), FOREIGN KEY (idRoom) REFERENCES Room (id), FOREIGN KEY (idLanguage) REFERENCES Language (id));

CREATE TABLE IF NOT EXISTS Exposition (id INT NOT NULL, name VARCHAR(100) NOT NULL, description VARCHAR(500) NULL, coverImageSrc VARCHAR(100) NULL, qrCodeLink VARCHAR(150) NULL, idRoomLanguage INT NOT NULL, PRIMARY KEY (id), FOREIGN KEY (idRoomLanguage) REFERENCES RoomLanguage (id));

CREATE TABLE IF NOT EXISTS Panel (id INT NOT NULL, idExposition INT NOT NULL, PRIMARY KEY (id), FOREIGN KEY (idExposition) REFERENCES Exposition (id));

CREATE TABLE IF NOT EXISTS Images (id INT NOT NULL, source VARCHAR(100) NOT NULL, PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS Audio (id INT NOT NULL, source VARCHAR(100) NOT NULL, idPanel INT NOT NULL, PRIMARY KEY (id), FOREIGN KEY (idPanel) REFERENCES Panel (id));

CREATE TABLE IF NOT EXISTS Text (id INT NOT NULL, text VARCHAR(400) NOT NULL, PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS Paragraph (idText INT NOT NULL, idPanel INT NOT NULL, PRIMARY KEY (idText, idPanel), FOREIGN KEY (idText) REFERENCES Text (id), FOREIGN KEY (idPanel) REFERENCES Panel (id));

CREATE TABLE IF NOT EXISTS AchievementsRoom (idRoom INT NOT NULL, idAchievements INT NOT NULL, PRIMARY KEY (idAchievements, idRoom), FOREIGN KEY (idRoom) REFERENCES Room (id));

CREATE TABLE IF NOT EXISTS PanelImages (idPanel INT NOT NULL, idImage INT NOT NULL, PRIMARY KEY (idPanel, idImage), FOREIGN KEY (idPanel) REFERENCES Panel (id), FOREIGN KEY (idImage) REFERENCES Images (id));

CREATE TABLE IF NOT EXISTS Achievement (id INT NOT NULL, points INT NOT NULL, idRoom INT NOT NULL, PRIMARY KEY (id), FOREIGN KEY (idRoom) REFERENCES Room (id));

CREATE TABLE IF NOT EXISTS CompletedAchievement (idAchievement INT NOT NULL, PRIMARY KEY (idAchievement), FOREIGN KEY (idAchievement) REFERENCES Achievement (id));
