
CREATE TABLE Room (id INT NOT NULL PRIMARY KEY, name VARCHAR(100) NOT NULL, description VARCHAR(500) NULL, coverImageSrc VARCHAR(45) NULL);
  
CREATE TABLE IF NOT EXISTS Exposition (id INT NOT NULL PRIMARY KEY, name VARCHAR(100) NOT NULL, description VARCHAR(500) NULL, coverImageSrc VARCHAR(100) NULL, qrCodeLink VARCHAR(150) NULL, idRoom INT NOT NULL, FOREIGN KEY (idRoom) REFERENCES Room (id));
	
CREATE TABLE IF NOT EXISTS Panel (id INT NOT NULL PRIMARY KEY, idExposition INT NOT NULL, FOREIGN KEY (idExposition) REFERENCES Exposition (id));
	
CREATE TABLE IF NOT EXISTS Images (id INT NOT NULL PRIMARY KEY, source VARCHAR(100) NOT NULL, idPanel INT NOT NULL, FOREIGN KEY (idPanel) REFERENCES Panel (id));
	
CREATE TABLE IF NOT EXISTS Audio (id INT NOT NULL PRIMARY KEY, source VARCHAR(100) NOT NULL, idPanel INT NOT NULL, FOREIGN KEY (idPanel) REFERENCES Panel (id));
	
CREATE TABLE IF NOT EXISTS Text (id INT NOT NULL PRIMARY KEY, text VARCHAR(400) NOT NULL);
  
CREATE TABLE IF NOT EXISTS Paragraph (idText INT NOT NULL, idPanel INT NOT NULL, PRIMARY KEY (idText, idPanel), FOREIGN KEY (idText) REFERENCES Text (id), FOREIGN KEY (idPanel) REFERENCES Panel (id));
	
CREATE TABLE Language (id INT NOT NULL PRIMARY KEY, language VARCHAR(2) NOT NULL, countryCode VARCHAR(2) NOT NULL);
  
CREATE TABLE RoomLanguage (idRoom INT NOT NULL, idLanguage INT NOT NULL, PRIMARY KEY (idRoom, idLanguage), FOREIGN KEY (idRoom) REFERENCES Room (id), FOREIGN KEY (idLanguage) REFERENCES Language (id));
	
CREATE TABLE AchievementsRoom (id INT NOT NULL PRIMARY KEY, idRoom INT NOT NULL, FOREIGN KEY (idRoom) REFERENCES Room (id));
